linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus.FieldLogger).Infof
          - (github.com/sirupsen/logrus.FieldLogger).Warnf
          - (github.com/sirupsen/logrus.FieldLogger).Errorf

  gofmt:
    simplify: true

  goimports:
    local-prefixes: csv2json

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
    config:
      G306: "0644"  # File permissions

  cyclop:
    max-complexity: 30  # TODO: Reduce to 15 after refactoring LoadRoutes
    skip-tests: true

  funlen:
    lines: 100
    statements: 60

  lll:
    line-length: 120
    tab-width: 4

linters:
  enable:
    # Core linters (always on)
    - errcheck       # Check for unchecked errors
    - gosimple       # Simplify code
    - govet          # Examine Go source code and report suspicious constructs
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Go static analysis
    - unused         # Check for unused constants, variables, functions and types

    # Style/formatting
    - gofmt          # Check if code is gofmt-ed
    - goimports      # Check if imports are formatted correctly
    - misspell       # Spell checker for comments
    - whitespace     # Detect leading/trailing whitespace

    # Code quality
    - gocritic       # Meta linter with 100+ checks
    - revive         # Replacement for golint
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Report unused function parameters
    - cyclop         # Check function complexity

    # Security
    - gosec          # Inspect source code for security issues

    # Performance
    - prealloc       # Find slice declarations that could be preallocated

    # Error handling
    - errorlint      # Find code that will cause problems with Go 1.13+ error wrapping

  disable:
    - typecheck      # Causes issues with some build configurations

  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - funlen
        - cyclop
        - govet  # fieldalignment in tests is less critical

    # Exclude test helper files
    - path: testdata/
      linters:
        - errcheck
        - gosec

    # Allow long lines in struct tags
    - linters:
        - lll
      source: "^\\s+`" # Struct tags

    # Temporarily allow octal literals until migration to 0o prefix
    - linters:
        - gocritic
      text: "octalLiteral"

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

issues:
  exclude-dirs:
    - vendor
    - testdata

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
